services:
    node:
        image: node:lts
        container_name: auriac_festival
        hostname: app
        restart: unless-stopped
        tty: true
        working_dir: /srv/app
        volumes:
            - ./:/srv/app
            - nodes_modules:/srv/app/node_modules
        ports:
            - "1337:1337"
        depends_on:
            -   database

    database:
        container_name: auriac_database
        restart: unless-stopped
        image: postgres:17
        env_file:
            - strapi/.env
        volumes:
            - strapi-data:/var/lib/postgresql/data/

volumes:
    nodes_modules:
    strapi-data:
